require 'dotstarlib/generator'
#require 'dotstarlib/color_filter'
#require 'dotstarlib/dim_filter'
#require 'dotstarlib/pulse_filter'
require 'dotstarlib/sin_generator'
require 'dotstarlib/sum_generator'
require 'dotstarlib/clamp_generator'
require 'dotstarlib/colorize_generator'
